version: '3.4'

services:
  fakeshop.api:
    build:
      context: .
      dockerfile: FakeShop.Api/Dockerfile
    ports:
      - 8080
      - 8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - SimpleProperty="from-code-compose"
    depends_on: 
      - seq_in_dc
      - rabbit_in_dc

  fakeshop.app:
    build:
      context: .
      dockerfile: FakeShop.App/Dockerfile
    ports:
      - 8080
      - 8081
    depends_on: 
      - seq_in_dc

  fakeshop.orderprocessor:
    build:
      context: .
      dockerfile: FakeShop.OrderProcessor/Dockerfile
    depends_on: 
      - seq_in_dc
      - rabbit_in_dc

  seq_in_dc:
    image: datalust/seq
    ports:
      - '8005:80'
    environment:
      - ACCEPT_EULA=Y

  rabbit_in_dc:
    image: rabbitmq:3-management
    ports:
      - 8088:15672
      
  
