version: '3.4'

services:
  fakeshop.api:
    image: ${DOCKER_REGISTRY-}fakeshopapi
    build:
      context: .
      dockerfile: FakeShop.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - SimpleProperty="from-compose"
    depends_on:
      - seq_in_dc

  seq_in_dc:
    image: datalust/seq
    ports:
      - '8005:80'
    environment:
      - ACCEPT_EULA=Y
