# Basic workflow to get started with Actions

name: Docker Image CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events only for the main branch
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - README.md
      - .vscode/**
      - .gitignore

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build the Docker image and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./FakeShop.Api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/fakeshopapi:latest, ${{ secrets.DOCKERHUB_USERNAME }}/fakeshopapi:${{ github.run_number }}
